### ISSUE TITLE
When running in Sitecore Managed Cloud PaaS, files are ignored

### ISSUE THREAD

**Issue by GurliGebis** [jbluemink/Find-overwritten-Sitecore-resource-items#2]
Hey,

When running in Sitecore Managed Cloud PaaS, the following is how the paths are defined:

```
<filePaths hint="list">
  <filePath>D:\home\site\wwwroot\App_Data/items/$(id)</filePath>
  <modulesFilePath>/sitecore modules/items/$(id)</modulesFilePath>
</filePaths>
```

This causes all files inside App_Data to be ignored, since `Sitecore.IO.FileUtil.MapPath` is called on it.
https://github.com/jbluemink/Find-overwritten-Sitecore-resource-items/blob/6096479df955ba5d74f0e0b41055b4343a204b1a/.serialization/serialization/uxbee.powershell/Uxbee/IAR%20-%20Reports/Reports/Find%20overwritten%20resource%20items.yml#L21

Instead, you should test if the path is absolute, and if that is the case, don't try and map it, but just use it as-is.

One way to test for it might be to test for a colon, since that would only be there in case of an absolute filesystem path.

```
Write-Host "path in config $filepath"
if ($filepath -like "*:*") {
    $serverpath = $filepath
} else {
    $serverpath = [Sitecore.IO.FileUtil]::MapPath("~/$filepath")
}
Write-Host "ServerPath = $serverpath"
```

The above is tested, and solves the issue.

**Comment by jbluemink** [comment]
Thank you for this detailed report..

**Comment by GurliGebis** [comment]
@jbluemink you're welcome.
Would it be possible for you to generate the `items.master.iaroverwrittenreport.dat` file again, with this change?

**Comment by jbluemink** [comment]
I updated the items.master.iaroverwrittenreport.dat (but did not tested on Azure webapps)

**Comment by GurliGebis** [comment]
Thanks

**Comment by GurliGebis** [comment]
@jbluemink I just tested on App Services, and it is working fine now 🙂
